// ---------------------------------------------------------------------------
// Bakes a canonical pair of transcripts into the repo.
//
//   node scripts/build-demo.mjs
//
// Replay mode exists from the first commit, per the build order, and this is
// what it replays on a fresh clone with no run history and no API key. Record
// the video against a replay; serve live mode on the public link.
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';

import { analyse } from '@mukeremshifa/tracer-core';
import { ATTACKS, CHAIN_PAGES, CONTROL_PAGES, deliveryGoalFor, attackById } from '../shared/attacks.js';
import { run } from '../server/src/loop.js';
import { getProvider } from '../server/src/providers/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..');

const pageStore = {};
for (const p of [...ATTACKS, ...CHAIN_PAGES, ...CONTROL_PAGES]) {
  const html = readFileSync(join(ROOT, 'server', 'src', 'range', p.id + '.html'), 'utf8');
  const dom = new JSDOM(html, { url: 'http://localhost/range/' + p.id });
  const r = analyse(dom.window.document, { url: '/range/' + p.id, window: dom.window, layout: false });
  pageStore['/range/' + p.id] = { spans: r.spans, report: r.report };
  dom.window.close();
}

const provider = await getProvider('simulated');
const goal = deliveryGoalFor(attackById('white-on-white'));

const unprotected = await run({ goal, protectedMode: false, pageStore, provider, label: 'demo/unprotected' });
const protectedRun = await run({ goal, protectedMode: true, pageStore, provider, label: 'demo/protected' });

writeFileSync(
  join(ROOT, 'server', 'data', 'demo-pair.json'),
  JSON.stringify(
    {
      note: 'Canonical demo transcripts, generated by scripts/build-demo.mjs. Analysed under jsdom, so the two box-geometry detectors did not run here; the browser runs them.',
      goal,
      unprotected,
      protected: protectedRun,
    },
    null,
    2,
  ),
  'utf8',
);

console.log('demo transcripts written');
console.log('  unprotected: ' + unprotected.outcome.verdict);
console.log('  protected:   ' + protectedRun.outcome.verdict);
