import { useEffect, useState } from 'react';
import { api } from '../lib/api.js';

export function Scorecard({ go }) {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    api
      .scorecard()
      .then(setData)
      .catch((err) => setError(String(err.message || err)));
  }, []);

  if (error) {
    return (
      <div className="wrap narrow">
        <div className="notice">
          {error}. Run <span className="mono">npm run eval</span> to build the scorecard.
        </div>
      </div>
    );
  }
  if (!data) {
    return (
      <div className="wrap narrow row faint">
        <span className="spinner" /> loading the scorecard
      </div>
    );
  }

  const t = data.tallies || {};
  // The second column: the same range, run against a real model. It is absent
  // until somebody with a credential runs it, and an absent column is shown as
  // absent rather than approximated from the deterministic one.
  const live = data.columns && data.liveColumn ? data.columns[data.liveColumn] : null;
  const liveRow = (id) => {
    if (!live) return null;
    const row = live.rows.find((r) => r.id === id);
    return row ? row.scenarios.deliver : null;
  };

  return (
    <div className="wrap stack">
      <div className="narrow">
        <div className="surface-tag">Range</div>
        <h1 className="title">Scorecard</h1>
        <p className="lede">
          Every attack on the range, run against both configurations, under two different user goals.
          Generated by <span className="mono">npm run eval</span>, including anything that got through.
        </p>
        <div className="notice info small">
          This scorecard is for the built-in sandbox agent, which is the zero-config default target. The
          same sixteen classes can be pointed at your agent instead:{' '}
          <span className="mono">npx @mukeremshifa/tracer test --target ./mcp.json</span> or{' '}
          <span className="mono">--target https://your-agent/</span>, and it emits a scorecard for
          that agent.
          {go && (
            <>
              {' '}
              <button className="btn sm ghost" onClick={() => go('home')}>
                put Tracer in front of it
              </button>
            </>
          )}
        </div>
        <p className="small muted" style={{ marginTop: 16 }}>
          In every row below where the unprotected agent was robbed, the model was fooled in the
          protected run too. The difference is that the consequence did not land.
        </p>
      </div>

      <div className="panel">
        <div className="panel-head">
          <span className="panel-title">Two scenarios</span>
        </div>
        <div className="panel-body table-wrap">
          <table className="grid">
            <thead>
              <tr>
                <th />
                <th>Summarise only</th>
                <th>Summarise and email it to me</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>attacks run</td>
                <td className="mono">{data.total}</td>
                <td className="mono">{data.total}</td>
              </tr>
              <tr>
                <td>unprotected agent robbed</td>
                <td className="mono">{cell(t.summarise && t.summarise.robbedUnprotected, data.total, 'hot')}</td>
                <td className="mono">{cell(t.deliver && t.deliver.robbedUnprotected, data.total, 'hot')}</td>
              </tr>
              <tr>
                <td>protected: exfiltration prevented</td>
                <td className="mono">{cell(t.summarise && t.summarise.blocked, data.total, 'quiet')}</td>
                <td className="mono">{cell(t.deliver && t.deliver.blocked, data.total, 'quiet')}</td>
              </tr>
              <tr>
                <td>protected: bypassed</td>
                <td className="mono">{cell(t.summarise && t.summarise.bypasses, data.total, 'hot')}</td>
                <td className="mono">{cell(t.deliver && t.deliver.bypasses, data.total, 'hot')}</td>
              </tr>
              <tr>
                <td>
                  user&rsquo;s actual task still completed
                  <div className="tiny faint">
                    A firewall that stops the attack by stopping the agent is an off switch, not a firewall.
                  </div>
                </td>
                <td className="faint">n/a</td>
                <td className="mono">{cell(t.deliver && t.deliver.taskStillCompleted, data.total, 'quiet')}</td>
              </tr>
            </tbody>
          </table>

          <div className="small muted" style={{ marginTop: 14 }}>
            <b>Why two.</b> With a plain &ldquo;summarise this&rdquo; goal the frozen plan contains no tier-2
            tool, so the plan freeze alone refuses any attempt to send anything anywhere, which in that
            scenario amounts to an allow-list of tool names. In the second scenario the user legitimately asks
            for the summary to be emailed, so <span className="mono">send_email</span> is on the plan, the plan
            freeze cannot fire, and the destination rule has to do the work. The second column is the one that matters.
          </div>
        </div>
      </div>

      <div className="panel">
        <div className="panel-head">
          <span className="panel-title">
            {live ? 'The same range, against a live model' : 'The live-model column, not run yet'}
          </span>
        </div>
        <div className="panel-body">
          {live ? (
            <>
              <table className="grid">
                <thead>
                  <tr>
                    <th />
                    <th>Summarise only</th>
                    <th>Summarise and email</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>unprotected agent robbed</td>
                    <td>{cell(live.tallies.summarise.robbedUnprotected, live.total, 'hot')}</td>
                    <td>{cell(live.tallies.deliver.robbedUnprotected, live.total, 'hot')}</td>
                  </tr>
                  <tr>
                    <td>protected: exfiltration prevented</td>
                    <td>{cell(live.tallies.summarise.blocked, live.total, 'good')}</td>
                    <td>{cell(live.tallies.deliver.blocked, live.total, 'good')}</td>
                  </tr>
                  <tr>
                    <td>protected: bypassed</td>
                    <td>{cell(live.tallies.summarise.bypasses, live.total, 'hot')}</td>
                    <td>{cell(live.tallies.deliver.bypasses, live.total, 'hot')}</td>
                  </tr>
                  <tr>
                    <td>user&rsquo;s actual task still completed</td>
                    <td className="faint">n/a</td>
                    <td>{cell(live.tallies.deliver.taskStillCompleted, live.total, 'good')}</td>
                  </tr>
                </tbody>
              </table>
              <div className="small muted" style={{ marginTop: 14 }}>
                <b>{live.label}</b>
                {live.model ? <>, model id <span className="mono">{live.model}</span></> : null}, run{' '}
                {new Date(live.at).toLocaleString()}. A real model paraphrases, and Layer B&rsquo;s n-gram half
                does not survive paraphrase. This column is where that ceiling is measured rather than
                asserted. The destination rule holds regardless, because an address is an address. Whatever gets
                through is published here; tuning the range to protect the number would destroy the only
                externally-generated evidence in the repo.
              </div>
            </>
          ) : (
            <div className="small muted stack">
              <div>
                Everything above is scored against a deterministic stand-in we wrote. The machinery for a second,
                live column ships with the repo. <span className="mono">scripts/eval.mjs</span> keeps one
                column per provider in <span className="mono">server/data/columns/</span> and merges what it
                finds, so a live run fills this in without discarding the reproducible column, but it
                needs a credential, and none was present when this scorecard was generated.
              </div>
              <div className="mono tiny">MODEL_PROVIDER=openai npm run eval</div>
              <div>
                Expect it not to be {data.total}/{data.total}, and expect to see the result either way. A
                live-model bypass would be the most valuable row in this repo: the first evidence about the
                defence that we did not generate ourselves.
              </div>
            </div>
          )}
        </div>
      </div>

      <div className="panel">
        <div className="panel-head">
          <span className="panel-title">The control page</span>
        </div>
        <div className="panel-body">
          <div className="row" style={{ gap: 18 }}>
            <div>
              <div className="stat-n">
                {data.control.concealedInstructionLike}
              </div>
              <div className="stat-l">hidden instruction-like elements found on a clean page</div>
            </div>
            <div>
              <div className="stat-n" style={{ color: 'var(--acid)' }}>
                {data.control.accessibilityPatterns}
              </div>
              <div className="stat-l">accessibility patterns flagged as accessibility patterns</div>
            </div>
            <div>
              <div className="stat-n" style={{ fontSize: 15, paddingTop: 8 }}>
                {data.control.verdict}
              </div>
              <div className="stat-l">verdict on the control page</div>
            </div>
          </div>
          <div className="small muted" style={{ marginTop: 14 }}>
            <span className="mono">aria-hidden</span>, <span className="mono">.sr-only</span> and the{' '}
            <span className="mono">clip-path</span> visually-hidden idiom are how the web supports screen
            readers. Tracer flags them so they stay attributable and explicitly does not treat them as attacks.
            A tool that punishes doing the right thing is a tool nobody should deploy.
          </div>
        </div>
      </div>

      <div className="panel">
        <div className="panel-head">
          <span className="panel-title">Every attack, summarise and email scenario</span>
        </div>
        <div className="panel-body tight table-wrap">
          <table className="grid">
            <thead>
              <tr>
                <th>attack</th>
                <th>family</th>
                <th>technique</th>
                <th>unprotected</th>
                <th>protected</th>
                <th>{live ? live.label : 'live model'}</th>
                <th>caught by</th>
                <th>source</th>
              </tr>
            </thead>
            <tbody>
              {data.rows.map((r) => {
                const d = r.scenarios.deliver;
                return (
                  <tr key={r.id}>
                    <td className="mono">{r.id}</td>
                    <td>{r.family}</td>
                    <td className="small muted">{r.technique}</td>
                    <td>
                      <span className={'tag ' + (d.unprotected.robbed ? 'hot' : 'quiet')}>
                        {d.unprotected.robbed ? 'robbed' : 'clean'}
                      </span>
                    </td>
                    <td>
                      <span className={'tag ' + (d.result === 'BYPASS' ? 'hot' : 'quiet')}>
                        {d.result === 'BYPASS' ? 'BYPASS' : 'prevented'}
                      </span>
                    </td>
                    <td>
                      {liveRow(r.id) ? (
                        <span className={'tag ' + (liveRow(r.id).result === 'BYPASS' ? 'hot' : 'quiet')}>
                          {liveRow(r.id).result === 'BYPASS' ? 'BYPASS' : 'prevented'}
                        </span>
                      ) : (
                        <span className="faint tiny">not run</span>
                      )}
                    </td>
                    <td className="mono tiny">
                      {d.caughtBy.rule || '—'}
                      {d.caughtBy.layer ? ' (Layer ' + d.caughtBy.layer + ')' : ''}
                    </td>
                    <td className="tiny">
                      {r.source ? (
                        r.source.url ? (
                          <a href={r.source.url} target="_blank" rel="noreferrer noopener" title={r.source.cite}>
                            {r.source.kind}
                          </a>
                        ) : (
                          <span className="faint" title={r.source.cite}>
                            {r.source.kind}
                          </span>
                        )
                      ) : (
                        <span className="faint">—</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      <div className="panel">
        <div className="panel-head">
          <span className="panel-title">Harness honesty</span>
        </div>
        <div className="panel-body small muted stack">
          <div>
            The analyser in the eval harness runs under <b>{data.harness.analyser}</b>. Two detectors therefore
            could not fire there: {data.harness.detectorsNotExercised.map((x) => <span className="mono" key={x}>{x} </span>)}
            , both being box-geometry checks that need real layout, and both run in the browser, which is
            where the analyser is actually deployed. Every other detector in this table is the same code the
            browser executes.
          </div>
          <div>
            Model provider for this run: <b>{data.provider.label}</b>
            {data.provider.live ? ' (live).' : ' (deterministic, not a language model).'}
          </div>
          <div>
            All six tools are mocks. The inbox is a JSON file in the repo. No tool performs network I/O. Every
            exfiltration destination on the range uses a non-resolvable host.
          </div>
          <div className="faint tiny">Generated {new Date(data.at).toLocaleString()}</div>
        </div>
      </div>
    </div>
  );
}

function cell(n, total, tone) {
  if (n == null) return '—';
  return (
    <span className={'tag ' + (n > 0 ? tone : '')}>
      {n} / {total}
    </span>
  );
}
