import { useEffect, useState } from 'react';
import { api } from '../lib/api.js';

export function Scorecard() {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    api
      .scorecard()
      .then(setData)
      .catch((err) => setError(String(err.message || err)));
  }, []);

  if (error) {
    return (
      <div className="wrap narrow">
        <div className="notice">
          {error}. Run <span className="mono">npm run eval</span> to build the scorecard.
        </div>
      </div>
    );
  }
  if (!data) {
    return (
      <div className="wrap narrow row faint">
        <span className="spinner" /> loading the scorecard
      </div>
    );
  }

  const t = data.tallies || {};

  return (
    <div className="wrap stack">
      <div className="narrow">
        <h1 className="title">Scorecard</h1>
        <p className="lede">
          Every attack on the range, run against both configurations, under two different user goals.
          Generated by <span className="mono">npm run eval</span> &mdash; including anything that got through.
        </p>
        <div className="claim">
          Tracer converts an invisible, unattributable compromise into a visible, attributable one, and
          structurally blocks the exfiltration class of consequences regardless of whether the model was
          fooled.
        </div>
        <p className="lede" style={{ marginTop: 14 }}>
          Note what is <i>not</i> claimed: that the model is not fooled. In every row below where the
          unprotected agent was robbed, the model was fooled in the protected run too. The difference is
          that the consequence did not land.
        </p>
      </div>

      <div className="panel">
        <div className="panel-head">
          <span className="panel-title">Two scenarios, because one of them would flatter us</span>
        </div>
        <div className="panel-body table-wrap">
          <table className="grid">
            <thead>
              <tr>
                <th />
                <th>Summarise only</th>
                <th>Summarise and email it to me</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>attacks run</td>
                <td className="mono">{data.total}</td>
                <td className="mono">{data.total}</td>
              </tr>
              <tr>
                <td>unprotected agent robbed</td>
                <td className="mono">{cell(t.summarise && t.summarise.robbedUnprotected, data.total, 'red')}</td>
                <td className="mono">{cell(t.deliver && t.deliver.robbedUnprotected, data.total, 'red')}</td>
              </tr>
              <tr>
                <td>protected: exfiltration prevented</td>
                <td className="mono">{cell(t.summarise && t.summarise.blocked, data.total, 'green')}</td>
                <td className="mono">{cell(t.deliver && t.deliver.blocked, data.total, 'green')}</td>
              </tr>
              <tr>
                <td>protected: bypassed</td>
                <td className="mono">{cell(t.summarise && t.summarise.bypasses, data.total, 'red')}</td>
                <td className="mono">{cell(t.deliver && t.deliver.bypasses, data.total, 'red')}</td>
              </tr>
              <tr>
                <td>
                  user&rsquo;s actual task still completed
                  <div className="tiny faint">
                    A firewall that stops the attack by stopping the agent is an off switch, not a firewall.
                  </div>
                </td>
                <td className="faint">n/a</td>
                <td className="mono">{cell(t.deliver && t.deliver.taskStillCompleted, data.total, 'green')}</td>
              </tr>
            </tbody>
          </table>

          <div className="small muted" style={{ marginTop: 14 }}>
            <b>Why two.</b> With a plain &ldquo;summarise this&rdquo; goal the frozen plan contains no tier-2
            tool, so the plan freeze alone refuses any attempt to send anything anywhere &mdash; which in that
            scenario amounts to an allow-list of tool names. In the second scenario the user legitimately asks
            for the summary to be emailed, so <span className="mono">send_email</span> is on the plan, the plan
            freeze cannot fire, and the destination rule has to do the work. Judge us on the second column.
          </div>
        </div>
      </div>

      <div className="panel">
        <div className="panel-head">
          <span className="panel-title">Control &mdash; does it cry wolf?</span>
        </div>
        <div className="panel-body">
          <div className="row" style={{ gap: 18 }}>
            <div>
              <div className="stat-n" style={{ color: '#6ce0a8' }}>
                {data.control.concealedInstructionLike}
              </div>
              <div className="stat-l">hidden instruction-like elements found on a clean page</div>
            </div>
            <div>
              <div className="stat-n" style={{ color: 'var(--teal)' }}>
                {data.control.accessibilityPatterns}
              </div>
              <div className="stat-l">accessibility patterns flagged as accessibility patterns</div>
            </div>
            <div>
              <div className="stat-n" style={{ fontSize: 15, paddingTop: 8 }}>
                {data.control.verdict}
              </div>
              <div className="stat-l">verdict on the control page</div>
            </div>
          </div>
          <div className="small muted" style={{ marginTop: 14 }}>
            <span className="mono">aria-hidden</span>, <span className="mono">.sr-only</span> and the{' '}
            <span className="mono">clip-path</span> visually-hidden idiom are how the web supports screen
            readers. Tracer flags them so they stay attributable and explicitly does not treat them as attacks.
            A tool that punishes doing the right thing is a tool nobody should deploy.
          </div>
        </div>
      </div>

      <div className="panel">
        <div className="panel-head">
          <span className="panel-title">Every attack &mdash; summarise and email scenario</span>
        </div>
        <div className="panel-body tight table-wrap">
          <table className="grid">
            <thead>
              <tr>
                <th>attack</th>
                <th>family</th>
                <th>technique</th>
                <th>unprotected</th>
                <th>protected</th>
                <th>caught by</th>
              </tr>
            </thead>
            <tbody>
              {data.rows.map((r) => {
                const d = r.scenarios.deliver;
                return (
                  <tr key={r.id}>
                    <td className="mono">{r.id}</td>
                    <td>{r.family}</td>
                    <td className="small muted">{r.technique}</td>
                    <td>
                      <span className={'tag ' + (d.unprotected.robbed ? 'red' : '')}>
                        {d.unprotected.robbed ? 'robbed' : 'clean'}
                      </span>
                    </td>
                    <td>
                      <span className={'tag ' + (d.result === 'BYPASS' ? 'red' : 'green')}>
                        {d.result === 'BYPASS' ? 'BYPASS' : 'prevented'}
                      </span>
                    </td>
                    <td className="mono tiny">
                      {d.caughtBy.rule || '—'}
                      {d.caughtBy.layer ? ' (Layer ' + d.caughtBy.layer + ')' : ''}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      <div className="panel">
        <div className="panel-head">
          <span className="panel-title">Harness honesty</span>
        </div>
        <div className="panel-body small muted stack">
          <div>
            The analyser in the eval harness runs under <b>{data.harness.analyser}</b>. Two detectors therefore
            could not fire there: {data.harness.detectorsNotExercised.map((x) => <span className="mono" key={x}>{x} </span>)}
            &mdash; both are box-geometry checks that need real layout, and both run in the browser, which is
            where the analyser is actually deployed. Every other detector in this table is the same code the
            browser executes.
          </div>
          <div>
            Model provider for this run: <b>{data.provider.label}</b>
            {data.provider.live ? ' (live).' : ' (deterministic, not a language model).'}
          </div>
          <div>
            All six tools are mocks. The inbox is a JSON file in the repo. No tool performs network I/O. Every
            exfiltration destination on the range uses a non-resolvable host.
          </div>
          <div className="faint tiny">Generated {new Date(data.at).toLocaleString()}</div>
        </div>
      </div>
    </div>
  );
}

function cell(n, total, tone) {
  if (n == null) return '—';
  return (
    <span className={'tag ' + (n > 0 ? tone : '')}>
      {n} / {total}
    </span>
  );
}
